version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Getting CodeArtifact auth token
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token \
          --domain nextwork \
          --domain-owner 811259913624 \
          --region ap-southeast-1 \
          --query authorizationToken \
          --output text`
  build:
    commands:
      - echo Build started on `date`
      - mvn -s settings.xml clean package

artifacts:
  files:
    - target/*.war
