version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  phases:
  pre_build:
    commands:
      - echo Logging in to CodeArtifact
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain nextwork --domain-owner 811259913624 --region ap-southeast-1 --query authorizationToken --output text)


  build:
    commands:
      - echo Build started on `date`
      - mvn -s settings.xml compile
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn -s settings.xml package
artifacts:
  files:
    - target/rogen-web-project.war
  discard-paths: no
